name: 'Comment artifacts'
on:
  workflow_run:
    workflows: ["Upload an artifact"]
    types: [completed]
jobs:
  post-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: message
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prefix: "Find your attachments below: "
